---
title: Data Scientist &amp; Software Engineer
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
url: https://recluse27.github.io
baseurl: "/tttt"
yourname: Vitalii Lazuka
location: Fremont, CA
linkedin: http://www.linkedin.com/vitaliilazuka
github: https://github.com/recluse27
kaggle: https://www.kaggle.com/evrial97
hackerrank: https://www.hackerrank.com/lazukav
